  CREATE TABLE BATCH_CNTL 
   (	JOB_NAME VARCHAR2(8 BYTE) NOT NULL ENABLE, 
      JOB_DESC VARCHAR2(1000 BYTE), 
	    STS VARCHAR2(1 BYTE) NOT NULL ENABLE, 
      START_TIME DATE, 
      END_TIME DATE, 
      LAST_COMMIT_TIME DATE, 
      RUNNING_IND VARCHAR2(1 BYTE) NOT NULL ENABLE, 
      PROGRESS_TEXT VARCHAR2(150 BYTE), 
      BATCH_TYPE VARCHAR2(6 BYTE), 
      CREATE_USER_ID VARCHAR2(30 BYTE) NOT NULL ENABLE, 
      CREATE_DATE DATE DEFAULT SYSDATE NOT NULL ENABLE, 
      UPDATE_USER_ID VARCHAR2(30 BYTE), 
      UPDATE_DATE DATE,
	 CONSTRAINT PK_BATCH_CNTL PRIMARY KEY (JOB_NAME));
/